### ISSUE TITLE
Supporting files not found after installing with setup.py

### ISSUE THREAD

**Issue by talensgj** [spacetelescope/awesimsoss#33]
After installing with setup.py I try running the example from the documentation but resource_filename('awesimsoss','files/scaled_spectrum.txt') fails with the following error:

Traceback (most recent call last):
  File "simulate.py", line 17, in <module>
    star = np.genfromtxt(resource_filename('awesimsoss','files/scaled_spectrum.txt'), unpack=True)
  File "/home/talens-irex/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1737, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/home/talens-irex/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/talens-irex/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /home/talens-irex/anaconda2/envs/py36/lib/python3.6/site-packages/awesimsoss-0.1.0-py3.6.egg/awesimsoss/files/scaled_spectrum.txt not found.

**Comment by talensgj** [comment]
Issue not present anymore in latest release.
